app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('events/search', 'EventsController@search');

Route::resource('files', 'FileEntryController');

Route::resource('events', 'EventsController');

Route::resource('menu-items', 'MenuItemController');

Route::get('attend/{id}', [
    'as' => 'attending.store',
    'uses' => 'AttendingController@store'
]);

Route::get('unattend/{id}', [
    'as' => 'attending.delete',
    'uses' => 'AttendingController@destroy'
]);

Route::get('order/add/{id}', [
    'as' => 'orders.store',
    'uses' => 'OrdersController@store'
]);

Route::get('order/remove/{id}', [
    'as' => 'orders.delete',
    'uses' => 'OrdersController@destroy'
]);

Route::group(['middleware' => 'admin'], function(){
    Route::resource('/admin/roles', 'RolesController');
    Route::get('/admin/roles/{id}/delete', [
        'as' => 'admin.roles.delete',
        'uses' => 'RolesController@destroy'
    ]);
});

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Food Club</title>

	<link href="{{ asset('/css/app.css') }}" rel="stylesheet">

	<!-- Fonts -->
	<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
    @yield('styles')

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body id="vue-app">
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle Navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/">Food Club</a>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><a href="{{ url('/home') }}">Home</a></li>
                    <li><a href="{{route('events.create')}}">Create Event</a></li>
                    <li><a href="{{ url('/') }}">Search</a></li>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					@if (Auth::guest())
						<li><a href="{{ url('/auth/login') }}">Login</a></li>
						<li><a href="{{ url('/auth/register') }}">Register</a></li>
					@else
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ Auth::user()->name }} <span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="{{ url('/auth/logout') }}">Logout</a></li>
							</ul>
						</li>
					@endif
				</ul>
			</div>
		</div>
	</nav>
    <div class="container">
        @yield('content')
    </div>


	<!-- Scripts -->
    <script src="/js/bundle.js"></script>
    <script src="/js/underscore.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
    @yield('scripts')
</body>
</html>

resources/views/home.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">My Events </div>

				<div class="panel-body">
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active"><a role="tab" href="#attending" data-toggle="tab">Attending</a></li>
                        <li role="presentation"><a role="tab" href="#hosting" data-toggle="tab">Hosting</a></li>
                    </ul>
                    <br/><br/>
                    <div class="tab-content">
                        <div class="tab-pane active" id="attending">
                            @include('events.list', ['events' => Auth::user()->events()->wherePivot('type', 'attending')->get()])
                        </div>
                        <div class="tab-pane" id="hosting">
                            @include('events.list', ['events' => Auth::user()->events()->wherePivot('type', 'host')->get()])
                        </div>
                    </div>

				</div>
			</div>
		</div>
	</div>
</div>
@endsection