app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('events/search', 'EventsController@search');

Route::resource('files', 'FileEntryController');

Route::resource('events', 'EventsController');

Route::resource('menu-items', 'MenuItemController');

Route::get('attend/{id}', [
    'as' => 'attending.store',
    'uses' => 'AttendingController@store'
]);

Route::get('unattend/{id}', [
    'as' => 'attending.delete',
    'uses' => 'AttendingController@destroy'
]);

Route::get('order/add/{id}', [
    'as' => 'orders.store',
    'uses' => 'OrdersController@store'
]);

Route::get('order/remove/{id}', [
    'as' => 'orders.delete',
    'uses' => 'OrdersController@destroy'
]);

Route::group(['middleware' => 'admin'], function(){
    Route::resource('/admin/roles', 'RolesController');
    Route::get('/admin/roles/{id}/delete', [
        'as' => 'admin.roles.delete',
        'uses' => 'RolesController@destroy'
    ]);
});

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'description'];

    public function users()
    {
        return $this->hasMany('App\User');
    }
}

app/Http/Controllers/RolesController.php
<?php

namespace App\Http\Controllers;

use App\Role;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class RolesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $roles = Role::all();

        return view('admin.roles.index', ['roles' => $roles]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.roles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        $input = $request->all();

        $role = Role::create($input);

        return redirect(route('admin.roles.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $role = Role::findOrFail($id);

        return view('admin.roles.show', ['role' => $role]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id);

        $role->delete();

        return redirect(route('admin.roles.index'));
    }
}

resources/views/admin/roles/create.blade.php
@extends('app')

@section('content')

    <form action="{{ route('admin.roles.store') }}" method="POST">
        <input type="hidden" value="{{csrf_token()}}" name="_token"/>
        @include('admin.roles.fields')
    </form>
@endsection

resources/views/admin/roles/fields.blade.php
<div class="form-group">
    <label for="name">Name</label>
    <input name="name" class="form-control" type="text"/>
</div>
<div class="form-group">
    <label for="description">Description</label>
    <textarea name="description" class="form-control" id="" cols="30" rows="10"></textarea>
</div>
<div class="form-group">
    <input type="submit" name="submit" class="btn btn-default"/>
</div>

resources/views/admin/roles/index.blade.php
@extends('app')

@section('content')
<div class="row">
    <h1 class="pull-left">Roles</h1>
    <a class="btn btn-primary pull-right" style="margin-top: 25px;" href="{!! route('admin.roles.create') !!}">Add New</a>
</div>
<div class="row">
    <table class="table">
        <thead>
        <th> Name</th>
        <th> Description</th>
        <th> actions</th>
        </thead>
        <tbody>
        @foreach($roles as $role)
            <tr>
                <td>
                    <a href="{!! route('admin.roles.show', [$role->id]) !!}">
                        {{$role->name}}
                    </a>
                </td>
                <td>
                    {{$role->description}}
                </td>
                <td>
                    <a href="{!! route('admin.roles.edit', [$role->id]) !!}" id="role-edit-{{$role->id}}"><i class="glyphicon glyphicon-edit"></i></a>
                    <a href="{!! route('admin.roles.delete', [$role->id]) !!}" id="role-delete-{{$role->id}}"><i class="glyphicon glyphicon-remove"></i>Delete</a>
                </td>
            </tr>
        @endforeach
        </tbody>

    </table>
</div>


@endsection

resources/views/admin/roles/show.blade.php
@extends('app')

@section('content')
    <div class="row">
        <div class="col-sm-6">
            <h1>{{$role->name}}</h1>
            <p>{{$role->description}}</p>
        </div>
    </div>
    @endsection