app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('events/search', 'EventsController@search');

Route::resource('files', 'FileEntryController');

Route::resource('events', 'EventsController');

Route::resource('menu-items', 'MenuItemController');

Route::get('attend/{id}', [
    'as' => 'attending.store',
    'uses' => 'AttendingController@store'
]);

Route::get('unattend/{id}', [
    'as' => 'attending.delete',
    'uses' => 'AttendingController@destroy'
]);

Route::get('order/add/{id}', [
    'as' => 'orders.store',
    'uses' => 'OrdersController@store'
]);

Route::get('order/remove/{id}', [
    'as' => 'orders.delete',
    'uses' => 'OrdersController@destroy'
]);

Route::group(['middleware' => 'admin'], function(){
    Route::resource('/admin/roles', 'RolesController');
    Route::get('/admin/roles/{id}/delete', [
        'as' => 'admin.roles.delete',
        'uses' => 'RolesController@destroy'
    ]);
});

app/Event.php
<?php

namespace App;

use App\FileEntry;
use Illuminate\Database\Eloquent\Model;

class Event extends Model
{

    public $fillable = ['name', 'description', 'address','lat', 'lng', 'thumbnail_id'];

    public static $rules =[
    ];

    public function thumbnail()
    {
        return $this->hasOne('\App\FileEntry', 'id' ,'thumbnail_id');
    }

    public function users()
    {
        return $this->belongsToMany('\App\User')->withPivot('type');
    }

    public function attendingCount()
    {
        return $this->users()->wherePivot('type','attending')->count();
    }

    public function menuItems()
    {
        return $this->hasMany('\App\MenuItem');
    }
}

app/Http/Controllers/EventsController.php
<?php

namespace App\Http\Controllers;

use App\Event;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class EventsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth', ['only' => ['create']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {



    }

    public function search(Request $request)
    {
        $input = $request->all();
        $center_lat = $input["lat"];
        $center_lng = $input["lng"];
        $radius = $input["radius"];

        $events = DB::select("SELECT *, ( 3959 * acos( cos( radians('{$center_lat}') ) * cos( radians( lat ) ) * cos( radians( lng ) - radians('{$center_lng}') ) + sin( radians('{$center_lat}') ) * sin( radians( lat ) ) ) ) AS distance FROM events HAVING distance < '{$radius}' ORDER BY distance LIMIT 0 , 20");

        return view('events.search', ['events' => $events, 'location' => $input]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('events.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        $user = Auth::user();
        $input = $request->all();

        $file = $input['file'];
        $file_id = $this->addThumbnail($file);
        $input['thumbnail_id'] = $file_id;

        $event = Event::create($input);

        $user->events()->save($event, ['type' => 'host']);

        return redirect(url('/home'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $event = Event::findOrFail($id);

        return view('events.show', ['event' => $event]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }


}

resources/views/events/create.blade.php
@extends('app')

@section('content')

    <div class="row">
        <div class="col-sm-6">
            <input id="pac-input" class="controls" type="text" placeholder="Search Box">
            <div id="map"></div>
        </div>
        <div class="col-sm-6">
            <form action="{{route('events.store')}}" method="POST" enctype="multipart/form-data" class="form">
                <input type="hidden" name="_token" value="{{csrf_token()}}"/>
                <input type="hidden" name="lat" value=""/>
                <input type="hidden" name="lng" value=""/>

                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" name="name" class="form-control"/>
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea name="description" class="form-control" id="" cols="30" rows="10"></textarea>
                </div>
                <div class="form-group">
                    <label for="address">Address:</label>
                    <input type="text" name="address" class="form-control" value="" disabled/>
                </div>
                <div class="form-group">
                    <label for="from">Date: </label>
                    <input type="date" id="from" class="form-control">
                </div>
                <div class="form-group">
                    <label for="to">Start time:</label>
                    <input type="time" id="to" class="form-control">
                </div>
                <div class="form-group">
                    <label for="to">End time:</label>
                    <input type="time" id="to" class="form-control">
                </div>
                <div class="form-group">
                    <label for="file">Thumbnail:</label>
                    <input type="file" name="file"/>
                </div>
                <div class="form-group">
                    <select name="tags" id="" class="form-control">
                        <option value="none">None</option>
                        <option value="vegan">Vegan</option>
                        <option value="vegitarian">Vegitarian</option>
                        <option value="gluten-free">Gluten free</option>
                    </select>
                </div>

                <div class="form-group">
                    <input type="submit" name="submit" class="btn btn-default"/>
                </div>
            </form>
        </div>
    </div>

@endsection

@section('scripts')

    <script>
        // This example adds a search box to a map, using the Google Place Autocomplete
        // feature. People can enter geographical searches. The search box will return a
        // pick list containing a mix of places and predicted search terms.

        function initAutocomplete() {
            var map = new google.maps.Map(document.getElementById('map'), {
                center: {lat: -37.8141, lng: 144.9633},
                zoom: 13,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            });

            // Create the search box and link it to the UI element.
            var input = document.getElementById('pac-input');
            var searchBox = new google.maps.places.SearchBox(input);
            map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

            // Bias the SearchBox results towards current map's viewport.
            map.addListener('bounds_changed', function() {
                searchBox.setBounds(map.getBounds());
            });

            var markers = [];
            // [START region_getplaces]
            // Listen for the event fired when the user selects a prediction and retrieve
            // more details for that place.
            searchBox.addListener('places_changed', function() {
                var places = searchBox.getPlaces();

                if (places.length == 0) {
                    return;
                }

                // Clear out the old markers.
                markers.forEach(function(marker) {
                    marker.setMap(null);
                });
                markers = [];

                // For each place, get the icon, name and location.
                var bounds = new google.maps.LatLngBounds();
                places.forEach(function(place) {
                    var icon = {
                        url: place.icon,
                        size: new google.maps.Size(71, 71),
                        origin: new google.maps.Point(0, 0),
                        anchor: new google.maps.Point(17, 34),
                        scaledSize: new google.maps.Size(25, 25)
                    };

                    // Create a marker for each place.
                    markers.push(new google.maps.Marker({
                        map: map,
                        icon: icon,
                        title: place.name,
                        position: place.geometry.location
                    }));

                    $('input[name="lat"]').val(markers[0].position.lat());
                    $('input[name="lng"]').val(markers[0].position.lng());
                    $('input[name="address"]').val(place.formatted_address);

                    if (place.geometry.viewport) {
                        // Only geocodes have viewport.
                        bounds.union(place.geometry.viewport);
                    } else {
                        bounds.extend(place.geometry.location);
                    }
                });
                map.fitBounds(bounds);
            });
            // [END region_getplaces]
        }


    </script>
    <script src="https://maps.googleapis.com/maps/api/js?libraries=places&callback=initAutocomplete"
            async defer></script>

@endsection
@section('styles')

    <style>

        #map {
            height: 500px;

        }
        .controls {
            margin-top: 10px;
            border: 1px solid transparent;
            border-radius: 2px 0 0 2px;
            box-sizing: border-box;
            -moz-box-sizing: border-box;
            height: 32px;
            outline: none;
            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
        }

        #pac-input {
            background-color: #fff;
            font-family: Roboto;
            font-size: 15px;
            font-weight: 300;
            margin-left: 12px;
            padding: 0 11px 0 13px;
            text-overflow: ellipsis;
            width: 300px;
        }

        #pac-input:focus {
            border-color: #4d90fe;
        }

        .pac-container {
            font-family: Roboto;
        }

        #type-selector {
            color: #fff;
            background-color: #4d90fe;
            padding: 5px 11px 0px 11px;
        }

        #type-selector label {
            font-family: Roboto;
            font-size: 13px;
            font-weight: 300;
        }
        #target {
            width: 345px;
        }

    </style>

@endsection

resources/views/events/list.blade.php
<ul>
    @foreach($events as $event)
        <div class="media">
            <div class="media-left">
                <a href="{{route('events.show', $event->id)}}">
                    <img class=" img product-thumbnail" src="{{route('files.show',$event->thumbnail_id )}}" alt="{{$event->name}}" height="80" width="80">
                </a>
            </div>
            <div class="media-body">
                <h4 class="media-heading">{{$event->name}}</h4>
                <p>{{str_limit($event->description, 200)}}</p>
            </div>
        </div>

    @endforeach
</ul>

resources/views/events/search.blade.php
@extends('app')

@section('content')

    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a data-toggle="collapse" href="#collapseSearch" aria-expanded="false" aria-controls="collapseExample">
                        Refine Search
                    </a>
                </div>
                <div class="panel-body collapse" id="collapseSearch">
                    <form class="form" action="/events/search">
                        <input type="hidden" name="lng" value="{{$location['lng']}}">
                        <input type="hidden" name="lat" value="{{$location['lat']}}">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox"> Vegan
                            </label>
                        </div>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox"> Vegitarian
                            </label>
                        </div>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox"> Gluten free
                            </label>
                        </div>
                        <div class="form-group">
                            <label for="points"> Distance </label>
                            <input type="text" id="textInput" name="radius" class="form-control" style="width: 20%" value="50">
                            <input type="range" name="points" value="50" min="0" max="50" onchange="updateTextInput(this.value);">
                        </div>
                        <div class="form-group">
                            <label for="from">From</label>
                            <input type="date" id="from" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="to">To</label>
                            <input type="date" id="to" class="form-control">
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Results </div>

                <div class="panel-body">
                    <ul class="nav nav-pills nav-stacked">
                        @foreach($events as $i => $event)
                            <li data-i="{{$i}}" class="map-sidebar">
                                <a href="{{route('events.show', $event->id)}}">
                                    <div class="media">
                                        <div class="media-left">

                                            <img class=" img product-thumbnail" src="{{route('files.show',$event->thumbnail_id )}}" alt="{{$event->name}}" height="80" width="80">

                                        </div>
                                        <div class="media-body">
                                            <h4 class="media-heading">{{$event->name}}</h4>
                                            <p>{{str_limit($event->description, 70)}}</p>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <hr/>

                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div><select id="locationSelect" style="width:100%;visibility:hidden"></select></div>
            <div id="map-canvas"></div>
        </div>

    </div>
@endsection
@section('styles')
    <style>

        @media (max-width: 768px) {
            #map-canvas{
                width:35.5em;
                height:37.5em;
                margin: auto;
            }
        }
        @media (min-width: 768px) {
            #map-canvas{
                width:43.75em;
                height:37.5em;
                margin: auto;
            }

        }
    </style>

@endsection

@section('scripts')
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script type="text/javascript">
        function updateTextInput(val) {
            document.getElementById('textInput').value=val;
        }
    </script>
    <script id="info-window-template" type="text/template">
        <div id="content">
            <img class=" img product-thumbnail" src="{{url('/')}}/files/<%= event.thumbnail_id %>" alt="<%= event.name %>" height="150px" width="300px">
            <div id="siteNotice">
            </div>
            <h1 id="firstHeading" class="firstHeading"><%= event.name %></h1>
            <div id="bodyContent">
                <p> <%= event.description %> </p>
                <p>Location: <%= event.address %> </p>
                <p><a href="/events/<%= event.id %>">Go To</a></p>
            </div>
        </div>
    </script>
    <script>


        var map;
        var gmarkers = [];
        var userLat = {{$location['lat']}};
        var userLng = {{$location['lng']}};
        var events = {!!json_encode($events) !!};
        var infoWindows = [];


        google.maps.event.addDomListener(window, 'load', initialize);
        $('.map-sidebar').on('mouseenter', openInfoWindow);
        $('.map-sidebar').on('mouseleave', closeInfoWindow);


        function initialize() {
            map = new google.maps.Map(document.getElementById('map-canvas'), {
                zoom: 11,
                center: {lat: userLat, lng: userLng}
            });

            _.each(events, addMarker);
        }

        function addMarker(mrker) {
            var latLng = new google.maps.LatLng(mrker.lat, mrker.lng);
            // Creating a marker and putting it on the map
            var marker = new google.maps.Marker({
                position: latLng,
                title: mrker.name
            });
            var contentTemplate = _.template($('#info-window-template').html());
            var contentString = contentTemplate({event: mrker});

            var infowindow = new google.maps.InfoWindow({
                content: contentString
            });

            google.maps.event.addListener(marker, 'click', function() {
                openInfoWindow = infowindow.open(map,marker);
                console.log(openInfoWindow);
            });
            marker.setMap(map);
            gmarkers.push(marker);
            infoWindows.push(infowindow);
        }

        function openInfoWindow(e){
            var i = $(this).data('i');
            google.maps.event.trigger(gmarkers[i], "click");

        }

        function closeInfoWindow(){
            var i = $(this).data('i');
            infoWindows[i].close();
        }







    </script>
@endsection

resources/views/events/show.blade.php
@extends('app')

@section('content')

    <div class="row">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="col-sm-4">
                    <img class=" img product-thumbnail" src="{{route('files.show',$event->thumbnail_id )}}" alt="{{$event->name}}" height="300px" width="300px">
                </div>
                <div class="col-sm-8">
                    <div class="caption-full">
                        <h4 class="pull-right">
                            <div class="col-xs-12">
                                <h3>Attending: {{ $event->attendingCount() }}</h3>

                            </div>
                            <br/>
                            <br/>
                            <div class="col-xs-12">
                                @include('partials.attendingForm')
                            </div>
                        </h4>
                        <h1>{{$event->name}}</h1>
                        <p>{{$event->description}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <menu-items></menu-items>
    @if(Auth::check())
        @if(Auth::user()->isHost($event->id))
            <div class="row">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Create new menu item (this panel is only visible if you are the host)
                    </div>
                    <div class="panel-body">
                        <form action="/menu-items" method="POST" enctype="multipart/form-data">
                            <input type="hidden" value="{{$event->id}}" name="event_id" />
                            <input type="hidden" name="_token" value="{{csrf_token()}}"/>
                            <div class="form-group">
                                <label for="name">Name:</label>
                                <input class="form-control" name="name" type="text"/>
                            </div>
                            <div class="form-group">
                                <label for="description">Description:</label>
                                <input class="form-control" name="description" type="text"/>
                            </div>
                            <div class="form-group">
                                <label for="price">Price:</label>
                                <input class="form-control" name="price" type="text"/>
                            </div>
                            <div class="form-group">
                                <label for="file">Thumbnail:</label>
                                <input type="file" name="file"/>
                            </div>
                            <div class="form-group">
                                <input type="submit" name="submit" class="btn btn-default"/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        @endif
    @endif
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                Menu Items
            </div>
            <div class="panel-body">



                @foreach($event->menuItems as $menuItem)

                    <div class="media">
                        <div class="media-left">

                            <img class=" img product-thumbnail" src="{{route('files.show',$menuItem->thumbnail_id )}}" alt="{{$menuItem->name}}" height="80" width="80">

                        </div>
                        <div class="media-body">
                            <div class="col-xs-4">
                                <h4 class="media-heading">{{$menuItem->name}}</h4>
                                <p>{{str_limit($menuItem->description, 70)}}</p>
                                <p>Price: {{$menuItem->price}}</p>
                            </div>

                                <div class="col-xs-6">
                                    @include('partials.orderForm')
                                </div>



                        </div>
                    </div>

                @endforeach

            </div>
        </div>
    </div>
    <br/><br/><br/><br/>
@endsection